# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sqlexample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sqlexample

  target 'sqlexample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sqlexampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'sqlexample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sqlexample-tvOS



end
